# -*- coding: utf-8 -*-
"""Parallel Interface.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pHqy68aOv84-W5KwhZ3lA2911YC8a4fE

# Parallel Interface

## AI-Based Personalized Banking Experience Using Random Forest

> Import Libraries and load dataset
"""

import kagglehub
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Download latest version
path = kagglehub.dataset_download("henriqueyamahata/bank-marketing")

print("Path to dataset files:", path)

df = pd.read_csv("/kaggle/input/bank-marketing/bank-additional-full.csv", sep=";")

"""> Display Dataset"""

print("First Five Rows:")
display(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nDataset Information:")
df.info()

print("\nStatistical Summary:")
display(df.describe())

print("\nMissing Values:")
display(df.isnull().sum())

print("\nDuplicate Records:")
print(df.duplicated().sum())

"""> Remove Duplicate Records"""

df = df.drop_duplicates()

"""> Display Clean Dataset"""

print("Clean Dataset:")
display(df.head())

df["y"].value_counts().plot(kind="bar")
plt.title("Target Distribution")
plt.show()

"""> Encode Categorical Features"""

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

"""> Define Features and Target"""

X = df.drop(["y"], axis=1)
y = df["y"]

"""> Split Dataset"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

"""> Train Random Forest Model"""

rf = RandomForestClassifier(
    n_estimators=500,
    max_depth=15,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features="sqrt",
    class_weight="balanced",
    random_state=42
)

rf.fit(X_train, y_train)
pred = rf.predict(X_test)

"""> Model Evaluation"""

print("Accuracy :", accuracy_score(y_test, pred))
print("Precision:", precision_score(y_test, pred))
print("Recall   :", recall_score(y_test, pred))
print("F1 Score :", f1_score(y_test, pred))

"""> Confusion Matrix"""

cm = confusion_matrix(y_test, pred)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)

disp.plot(cmap="RdPu", colorbar=False)
plt.title("Confusion Matrix")
plt.show()

"""> Feature Importance Analysis"""

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print(importance)

importance = importance.head(10)

plt.figure(figsize=(8,5))

plt.barh(
    importance["Feature"],
    importance["Importance"]
)

plt.title("Top 10 Important Features")

plt.xlabel("Importance")

plt.gca().invert_yaxis()

plt.show()

"""## Conclusion

The Random Forest model successfully demonstrated how Artificial Intelligence can analyze banking data and customer behavior. Although this prototype was trained using a public banking dataset, the same approach can be integrated into the Parallel Interface system to personalize the banking experience by recommending the most suitable interface for each customer based on financial behavior.
"""